control_frame: gps_baro_origin
N: 4
clearance: 2.5
clearance_obstacles: 0.5
max_vel: 30
rho_0: 3.0
rho_1 : 3.0
r : 0.4
m_soft : 1.5 
m_hard : 3
ros_rate : 10 
ts : 0.01
Kv : 0.25
lambda: 20
v_max: 2.0
UAV_names: [uav1, uav2, uav3, uav4]
